from __future__ import annotations

import hashlib
import json
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Sequence

AUDIT_DIR_NAME = ".business_ai_audit"


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    p = Path(path)
    with p.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def audit_dir(base_dir: str | None = None) -> Path:
    base = Path(base_dir).expanduser().resolve() if base_dir else Path.home()
    d = base / AUDIT_DIR_NAME
    d.mkdir(parents=True, exist_ok=True)
    return d


def create_audit_record(
    input_files: Sequence[str],
    options: Dict[str, Any],
    generated_outputs: Sequence[Dict[str, Any]],
    base_dir: str | None = None,
) -> str:
    d = audit_dir(base_dir)
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    record = {
        "timestamp_utc": timestamp,
        "input_files": [
            {
                "path": str(Path(f).expanduser().resolve()),
                "name": Path(f).name,
                "sha256": sha256_file(f) if Path(f).exists() else None,
            }
            for f in input_files
        ],
        "options": options,
        "generated_outputs": list(generated_outputs),
        "status": "draft",
    }
    out = d / f"generation_{timestamp}_{int(time.time()*1000)%100000}.json"
    out.write_text(json.dumps(record, indent=2, ensure_ascii=False, default=str), encoding="utf-8")
    update_approval_register(generated_outputs, audit_record=str(out), base_dir=base_dir)
    return str(out)


def approval_register_path(base_dir: str | None = None) -> Path:
    return audit_dir(base_dir) / "approval_register.json"


def load_approval_register(base_dir: str | None = None) -> Dict[str, Any]:
    path = approval_register_path(base_dir)
    if not path.exists():
        return {"items": []}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {"items": []}


def update_approval_register(generated_outputs: Sequence[Dict[str, Any]], audit_record: str, base_dir: str | None = None) -> str:
    register = load_approval_register(base_dir)
    items = register.setdefault("items", [])
    now = datetime.now(timezone.utc).isoformat()
    for output_group in generated_outputs:
        if not output_group:
            continue
        paths = []
        if isinstance(output_group.get("exports"), dict):
            paths.extend(output_group["exports"].get("outputs", {}).values())
        if output_group.get("path"):
            paths.append(output_group["path"])
        for p in sorted(set(str(x) for x in paths if x)):
            items.append({
                "path": p,
                "status": "draft",
                "created_utc": now,
                "updated_utc": now,
                "audit_record": audit_record,
                "notes": "Generated by Local Business AI Skill",
            })
    path = approval_register_path(base_dir)
    path.write_text(json.dumps(register, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(path)


def set_output_status(path: str, status: str, notes: str = "", base_dir: str | None = None) -> Dict[str, Any]:
    allowed = {"draft", "reviewed", "approved", "sent", "rejected", "revised"}
    if status not in allowed:
        raise ValueError(f"Invalid status '{status}'. Use one of {sorted(allowed)}")
    register = load_approval_register(base_dir)
    target = str(Path(path).expanduser().resolve())
    now = datetime.now(timezone.utc).isoformat()
    found = False
    for item in register.setdefault("items", []):
        if str(Path(item.get("path", "")).expanduser().resolve()) == target:
            item["status"] = status
            item["updated_utc"] = now
            if notes:
                item["notes"] = notes
            found = True
    if not found:
        register["items"].append({"path": target, "status": status, "created_utc": now, "updated_utc": now, "notes": notes})
    approval_register_path(base_dir).write_text(json.dumps(register, indent=2, ensure_ascii=False), encoding="utf-8")
    return register
